import Head from 'next/head'
import Image from 'next/image'

import Content from './components/content'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Eight Knot Inc.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Content>
      <main>
        <h1>
         TOP PAGE
        </h1>
      </main>
  </Content>

    </div>
  )
}
