import Head from 'next/head';
import Image from 'next/image';
import Content from './components/content';
import Date from './components/date';
import { client } from '../libs/client';
import Link from 'next/link';
import Styles from '../styles/components.module.css';
import HomeIcon from '../public/icon/home.svg';
import NewsIcon from '../public/icon/news.svg';
import BlogIcon from '../public/icon/blog.svg';
import AboutIcon from '../public/icon/about.svg';
import ContactIcon from '../public/icon/contact.svg';
import FacebookIcon from '../public/icon/facebook.svg';
import TwitterIcon from '../public/icon/twitter.svg';
import BlankIcon from '../public/icon/blank.svg';
import TeamIcon from '../public/icon/team.svg';
import BgLogo from '../public/icon/EightKnot_mark_bg.svg';
import Logo from '../public/icon/EightKnot_logo_horizontal.svg';
import Eyecatch from '../public/icon/EightKnotEyecacthBg.svg';

interface Article {
  id: string;
  title: string;
  category: {
    name: string;
  };
  publishedAt: string;
  blankLink: string;
  thumb: string;
  pubDate: string;
  link: string;
  contentSnippet: string;
  image: {
    url: string;
  };
  name: string;
  post: string;
  url: string;
}
interface Contents {
  contents: Article[];
}

export default function Home({
  newsItem,
  staffItem,
  noteItem,
}: {
  newsItem: {
    id: string;
    title: string;
    category: {
      name: string;
    };
    publishedAt: string;
    blankLink: string;
  }[];
  staffItem: {
    id: string;
    name: string;
    post: string;
    image: {
      url: string;
    };
  }[];
  noteItem: {
    thumb: string;
    title: string;
    pubDate: string;
    link: string;
    contentSnippet: string;
  }[];
}): JSX.Element {
  return (
    <div>
      <Head>
        <title>Eight Knot Inc.</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={Styles.eyecatch}>
        <Eyecatch />
        <p className={Styles.catchcopy}>
          あらゆる水上モビリティを
          <br />
          ロボティクスとAIで自律化する
        </p>
      </div>
      <Content>
        <main>
          <section className={`${Styles.bg_dark} ${Styles.news_section}`}>
            <div className={`${Styles.news_inner} ${Styles.news_flex}`}>
              <div className={Styles.news_flex_left}>
                <div className={Styles.headline_box}>
                  <h2 className={`${Styles.headline} ${Styles.white}`}>
                    <NewsIcon />
                    <span className={Styles.headline_txt}>News</span>
                  </h2>
                  <p className={Styles.sub_headline}>
                    Notice from
                    <br />
                    the Our Company
                  </p>
                </div>
              </div>
              <div className={Styles.news_flex_right}>
                <ul className={Styles.news_list}>
                  {newsItem.map((news) => (
                    <li key={news.id}>
                      {news.blankLink ? (
                        <Link href={news.blankLink}>
                          <a target='_blank'>
                            <h3>
                              <BlankIcon />
                              {news.title}
                            </h3>
                            <p className={Styles.post_date}>
                              <Date dateString={news.publishedAt} />
                              <span className={Styles.category_name}>
                                {news.category && `${news.category.name}`}
                              </span>
                            </p>
                          </a>
                        </Link>
                      ) : (
                        <Link href={`/news/${news.id}`}>
                          <a>
                            <h3>{news.title}</h3>
                            <p className={Styles.post_date}>
                              <Date dateString={news.publishedAt} />
                              <span className={Styles.category_name}>
                                {news.category && `${news.category.name}`}
                              </span>
                            </p>
                          </a>
                        </Link>
                      )}
                    </li>
                  ))}
                </ul>
                <div className={Styles.view_more_box}>
                  <Link href='/news'>
                    <a className={`${Styles.btn} ${Styles.btn_white}`}>View More</a>
                  </Link>
                </div>
              </div>
            </div>
          </section>
          <section className={Styles.bg_logo}>
            <div className={Styles.section_inner}>
              <div className={Styles.headline_box}>
                <h2 className={`${Styles.headline} ${Styles.white}`}>
                  <TeamIcon />
                  <span className={Styles.headline_txt}>Team</span>
                </h2>
                <p className={Styles.sub_headline}>
                  Introduce
                  <br />
                  Our Team Staff
                </p>
              </div>

              <ul className={Styles.team_list}>
                {staffItem.map((staff) => (
                  <li key={staff.id}>
                    <div className={`${Styles.img_circle} ${Styles.team_list_img}`}>
                      <img src={staff.image.url} />
                    </div>
                    <div className={Styles.team_list_info}>
                      <h3 className={Styles.team_list_name}> {staff.name}</h3>
                      <p className={Styles.team_list_post}> {staff.post}</p>
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          </section>
          <section>
            <div className={Styles.section_inner}>
              <div className={Styles.headline_box}>
                <h2 className={Styles.headline}>
                  <BlogIcon />
                  <span className={Styles.headline_txt}>Blog</span>
                </h2>
                <p className={Styles.sub_headline}>List of Blog Post</p>
              </div>
              <ul className={Styles.blog}>
                {noteItem.map((note) => (
                  <li key={note.title}>
                    <Link href={note.link}>
                      <a target='_blank'>
                        <img className={Styles.blog_thumbnail} src={note.thumb} alt={note.title} />
                        <div className={Styles.blog_txt}>
                          <h3 className={Styles.blog_title}>{note.title}</h3>
                          <p className={Styles.blog_date}>{note.pubDate}</p>
                          <p className={Styles.blog_descripiton}> {note.contentSnippet}</p>
                        </div>
                      </a>
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          </section>
        </main>
      </Content>
    </div>
  );
}

import Parser from 'rss-parser';
import { ST } from 'next/dist/shared/lib/utils';

export const getStaticProps = async () => {
  const newsData: Contents = await client.get({ endpoint: 'news' });
  const staffData: Contents = await client.get({ endpoint: 'staff' });

  const parser = new Parser({
    customFields: {
      item: [['media:thumbnail', 'thumb', { keepArray: true }]],
    },
  });
  const rssNote = await parser.parseURL('https://note.com/8kt/rss');

  return {
    props: {
      noteItem: rssNote.items,
      newsItem: newsData.contents,
      staffItem: staffData.contents,
    },
  };
};
